name: GitHub raw url
  # You may pin to the exact commit or the version.
  # uses: ActionCloud/github-raw-url@3d0c9becc4c40721044757b088e2f6da03b7a7e8
  uses: ActionCloud/github-raw-url@v1
  with:
    # A normal GitHub url
    github-url: # optional
